"""Dossier service — CRUD + lifecycle binding to the workflow engine."""

from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.enums import DossierStatus, NodeRunStatus, WorkflowRunStatus
from app.modules.credito.models.dossier import CreditDossier
from app.shared.workflow.models.run import WorkflowRun
from app.shared.workflow.services import engine as workflow_engine


class DossierServiceError(RuntimeError):
    """Domain-level dossier error."""


async def create_dossier(
    db: AsyncSession,
    *,
    tenant_id: UUID,
    target_cnpj: str,
    target_name: str,
    workflow_definition_id: UUID,
    analyst_id: UUID | None = None,
    operation_type: str | None = None,
    requested_amount: Any | None = None,
    requested_term_days: int | None = None,
    notes: str | None = None,
) -> CreditDossier:
    """Create a dossier and start its workflow run.

    The dossier and workflow run are created in the same transaction. The
    caller is responsible for committing.
    """
    dossier = CreditDossier(
        tenant_id=tenant_id,
        target_cnpj=target_cnpj,
        target_name=target_name,
        workflow_definition_id=workflow_definition_id,
        analyst_id=analyst_id,
        operation_type=operation_type,
        requested_amount=requested_amount,
        requested_term_days=requested_term_days,
        notes=notes,
        status=DossierStatus.DRAFT,
    )
    db.add(dossier)
    await db.flush()

    # Kick off the workflow run.
    run = await workflow_engine.start_run(
        db,
        tenant_id=tenant_id,
        definition_id=workflow_definition_id,
        trigger_type="manual",
        trigger_data={
            "dossier_id": str(dossier.id),
            "target_cnpj": target_cnpj,
            # Alias: templates frequentes usam `{{trigger.cnpj}}` por ser
            # mais curto e natural. Mantemos os dois pra que ambos os
            # caminhos funcionem sem o usuario precisar saber qual a chave
            # canonica.
            "cnpj": target_cnpj,
            "target_name": target_name,
        },
        initiated_by=analyst_id,
    )

    dossier.workflow_run_id = run.id
    dossier.status = _status_from_run(run)
    await db.flush()
    # Refresh to populate server-defaults (`created_at`, `updated_at`) that
    # were generated by Postgres on INSERT but are not yet on the Python
    # object. Without this, accessing `dossier.updated_at` after commit (e.g.
    # via Pydantic `model_validate`) triggers a lazy refresh which fails in
    # async context with MissingGreenlet.
    await db.refresh(dossier)
    return dossier


async def get_dossier(
    db: AsyncSession, *, tenant_id: UUID, dossier_id: UUID
) -> CreditDossier | None:
    return (
        await db.execute(
            select(CreditDossier).where(
                CreditDossier.tenant_id == tenant_id,
                CreditDossier.id == dossier_id,
            )
        )
    ).scalar_one_or_none()


async def list_dossiers(
    db: AsyncSession,
    *,
    tenant_id: UUID,
    status: DossierStatus | None = None,
    analyst_id: UUID | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[CreditDossier]:
    query = select(CreditDossier).where(CreditDossier.tenant_id == tenant_id)
    if status is not None:
        query = query.where(CreditDossier.status == status)
    if analyst_id is not None:
        query = query.where(CreditDossier.analyst_id == analyst_id)
    query = query.order_by(CreditDossier.created_at.desc()).limit(limit).offset(offset)
    return list((await db.execute(query)).scalars().all())


async def sync_status_from_workflow(
    db: AsyncSession,
    *,
    dossier: CreditDossier,
) -> CreditDossier:
    """Update `dossier.status` based on the bound workflow run.

    Called after every workflow event that may have transitioned the run.
    """
    if dossier.workflow_run_id is None:
        return dossier
    run = (
        await db.execute(
            select(WorkflowRun).where(WorkflowRun.id == dossier.workflow_run_id)
        )
    ).scalar_one_or_none()
    if run is None:
        return dossier
    dossier.status = _status_from_run(run)
    if run.status == WorkflowRunStatus.COMPLETED and dossier.finalized_at is None:
        dossier.finalized_at = run.completed_at
    await db.flush()
    return dossier


def _status_from_run(run: WorkflowRun) -> DossierStatus:
    """Derive DossierStatus from WorkflowRunStatus + node-level signals."""
    rs = run.status
    if rs == WorkflowRunStatus.PENDING:
        return DossierStatus.DRAFT
    if rs == WorkflowRunStatus.RUNNING:
        # Heuristic: if we're past document_request, we're analyzing; else collecting.
        return DossierStatus.ANALYZING
    if rs == WorkflowRunStatus.PAUSED:
        return DossierStatus.REVIEW
    if rs == WorkflowRunStatus.COMPLETED:
        return DossierStatus.FINALIZED
    if rs == WorkflowRunStatus.CANCELLED:
        return DossierStatus.CANCELLED
    if rs == WorkflowRunStatus.FAILED:
        return DossierStatus.REVIEW  # surfaces in UI as needing analyst intervention
    return DossierStatus.DRAFT


__all__ = [
    "DossierServiceError",
    "NodeRunStatus",
    "create_dossier",
    "get_dossier",
    "list_dossiers",
    "sync_status_from_workflow",
]
