"""warehouse: wh_movimento_caixa

Revision ID: 03a6eff064c0
Revises: bc3a4b2d07da
Create Date: 2026-04-25 12:57:33.905741

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03a6eff064c0'
down_revision: str | None = 'bc3a4b2d07da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_movimento_caixa',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_liquidacao', sa.Date(), nullable=False),
    sa.Column('carteira_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('carteira_cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('carteira_cliente_doc', sa.String(length=14), nullable=False),
    sa.Column('tipo_de_registro', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('historico_traduzido', sa.Text(), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('conta_corrente', sa.String(length=30), nullable=True),
    sa.Column('digito', sa.String(length=5), nullable=True),
    sa.Column('id_conta', sa.Integer(), nullable=True),
    sa.Column('conta_investimento', sa.String(length=50), nullable=True),
    sa.Column('entradas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saidas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_movimento_caixa')
    )
    op.create_index(op.f('ix_wh_movimento_caixa_carteira_cliente_doc'), 'wh_movimento_caixa', ['carteira_cliente_doc'], unique=False)
    op.create_index(op.f('ix_wh_movimento_caixa_carteira_cliente_id'), 'wh_movimento_caixa', ['carteira_cliente_id'], unique=False)
    op.create_index(op.f('ix_wh_movimento_caixa_data_liquidacao'), 'wh_movimento_caixa', ['data_liquidacao'], unique=False)
    op.create_index(op.f('ix_wh_movimento_caixa_source_id'), 'wh_movimento_caixa', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_movimento_caixa_source_type'), 'wh_movimento_caixa', ['source_type'], unique=False)
    op.create_index('ix_wh_movimento_caixa_tenant_carteira', 'wh_movimento_caixa', ['tenant_id', 'carteira_cliente_doc', 'data_liquidacao'], unique=False)
    op.create_index('ix_wh_movimento_caixa_tenant_data', 'wh_movimento_caixa', ['tenant_id', 'data_liquidacao'], unique=False)
    op.create_index(op.f('ix_wh_movimento_caixa_tenant_id'), 'wh_movimento_caixa', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_movimento_caixa_tenant_id'), table_name='wh_movimento_caixa')
    op.drop_index('ix_wh_movimento_caixa_tenant_data', table_name='wh_movimento_caixa')
    op.drop_index('ix_wh_movimento_caixa_tenant_carteira', table_name='wh_movimento_caixa')
    op.drop_index(op.f('ix_wh_movimento_caixa_source_type'), table_name='wh_movimento_caixa')
    op.drop_index(op.f('ix_wh_movimento_caixa_source_id'), table_name='wh_movimento_caixa')
    op.drop_index(op.f('ix_wh_movimento_caixa_data_liquidacao'), table_name='wh_movimento_caixa')
    op.drop_index(op.f('ix_wh_movimento_caixa_carteira_cliente_id'), table_name='wh_movimento_caixa')
    op.drop_index(op.f('ix_wh_movimento_caixa_carteira_cliente_doc'), table_name='wh_movimento_caixa')
    op.drop_table('wh_movimento_caixa')
    # ### end Alembic commands ###
