"""warehouse: aquisicao + liquidacao + operacao remessa (custodia)

Revision ID: 03c0d6a48f32
Revises: 32a2d607d5c4
Create Date: 2026-04-25 17:24:38.451674

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03c0d6a48f32'
down_revision: str | None = '32a2d607d5c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_aquisicao_recebivel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('fundo_doc', sa.String(length=14), nullable=False),
    sa.Column('fundo_nome', sa.String(length=200), nullable=False),
    sa.Column('cedente_doc', sa.String(length=14), nullable=False),
    sa.Column('cedente_nome', sa.String(length=200), nullable=False),
    sa.Column('sacado_doc', sa.String(length=14), nullable=False),
    sa.Column('sacado_nome', sa.String(length=200), nullable=False),
    sa.Column('id_recebivel', sa.String(length=32), nullable=False),
    sa.Column('seu_numero', sa.String(length=50), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=False),
    sa.Column('tipo_recebivel', sa.String(length=50), nullable=False),
    sa.Column('valor_compra', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_vencimento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('prazo_recebivel', sa.Integer(), nullable=False),
    sa.Column('taxa_aquisicao', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_aquisicao_recebivel')
    )
    op.create_index(op.f('ix_wh_aquisicao_recebivel_cedente_doc'), 'wh_aquisicao_recebivel', ['cedente_doc'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_data_aquisicao'), 'wh_aquisicao_recebivel', ['data_aquisicao'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_fundo_doc'), 'wh_aquisicao_recebivel', ['fundo_doc'], unique=False)
    op.create_index('ix_wh_aquisicao_recebivel_id_recebivel', 'wh_aquisicao_recebivel', ['id_recebivel'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_sacado_doc'), 'wh_aquisicao_recebivel', ['sacado_doc'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_source_id'), 'wh_aquisicao_recebivel', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_source_type'), 'wh_aquisicao_recebivel', ['source_type'], unique=False)
    op.create_index('ix_wh_aquisicao_recebivel_tenant_fundo_cedente', 'wh_aquisicao_recebivel', ['tenant_id', 'fundo_doc', 'cedente_doc', 'data_aquisicao'], unique=False)
    op.create_index('ix_wh_aquisicao_recebivel_tenant_fundo_data', 'wh_aquisicao_recebivel', ['tenant_id', 'fundo_doc', 'data_aquisicao'], unique=False)
    op.create_index('ix_wh_aquisicao_recebivel_tenant_fundo_sacado', 'wh_aquisicao_recebivel', ['tenant_id', 'fundo_doc', 'sacado_doc', 'data_aquisicao'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_tenant_id'), 'wh_aquisicao_recebivel', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_aquisicao_recebivel_tipo_recebivel'), 'wh_aquisicao_recebivel', ['tipo_recebivel'], unique=False)
    op.create_table('wh_liquidacao_recebivel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('fundo_doc', sa.String(length=14), nullable=False),
    sa.Column('fundo_nome', sa.String(length=200), nullable=False),
    sa.Column('cedente_doc', sa.String(length=14), nullable=False),
    sa.Column('cedente_nome', sa.String(length=200), nullable=False),
    sa.Column('sacado_doc', sa.String(length=14), nullable=False),
    sa.Column('sacado_nome', sa.String(length=200), nullable=False),
    sa.Column('id_recebivel', sa.String(length=32), nullable=False),
    sa.Column('seu_numero', sa.String(length=50), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=False),
    sa.Column('numero_correspondente', sa.String(length=100), nullable=True),
    sa.Column('tipo_recebivel', sa.String(length=50), nullable=False),
    sa.Column('valor_aquisicao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_vencimento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ajuste', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxa_aquisicao', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('st_recebivel', sa.String(length=20), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_liquidacao_recebivel')
    )
    op.create_index(op.f('ix_wh_liquidacao_recebivel_cedente_doc'), 'wh_liquidacao_recebivel', ['cedente_doc'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_data_posicao'), 'wh_liquidacao_recebivel', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_fundo_doc'), 'wh_liquidacao_recebivel', ['fundo_doc'], unique=False)
    op.create_index('ix_wh_liquidacao_recebivel_id_recebivel', 'wh_liquidacao_recebivel', ['id_recebivel'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_sacado_doc'), 'wh_liquidacao_recebivel', ['sacado_doc'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_source_id'), 'wh_liquidacao_recebivel', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_source_type'), 'wh_liquidacao_recebivel', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_st_recebivel'), 'wh_liquidacao_recebivel', ['st_recebivel'], unique=False)
    op.create_index('ix_wh_liquidacao_recebivel_tenant_fundo_data', 'wh_liquidacao_recebivel', ['tenant_id', 'fundo_doc', 'data_posicao'], unique=False)
    op.create_index('ix_wh_liquidacao_recebivel_tenant_fundo_sacado', 'wh_liquidacao_recebivel', ['tenant_id', 'fundo_doc', 'sacado_doc', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_tenant_id'), 'wh_liquidacao_recebivel', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_liquidacao_recebivel_tipo_recebivel'), 'wh_liquidacao_recebivel', ['tipo_recebivel'], unique=False)
    op.create_table('wh_operacao_remessa',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_importacao', sa.Date(), nullable=False),
    sa.Column('fundo_doc', sa.String(length=14), nullable=False),
    sa.Column('fundo_nome', sa.String(length=200), nullable=False),
    sa.Column('gestor_doc', sa.String(length=14), nullable=False),
    sa.Column('gestor_nome', sa.String(length=200), nullable=False),
    sa.Column('cedente_doc', sa.String(length=14), nullable=False),
    sa.Column('cedente_nome', sa.String(length=200), nullable=False),
    sa.Column('id_operacao_recebivel', sa.String(length=32), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=100), nullable=False),
    sa.Column('nome_arquivo_entrada', sa.String(length=100), nullable=False),
    sa.Column('tipo_recebivel', sa.String(length=50), nullable=False),
    sa.Column('remessa', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reembolso', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recompra', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('coobrigacao', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_operacao_remessa')
    )
    op.create_index(op.f('ix_wh_operacao_remessa_cedente_doc'), 'wh_operacao_remessa', ['cedente_doc'], unique=False)
    op.create_index(op.f('ix_wh_operacao_remessa_data_importacao'), 'wh_operacao_remessa', ['data_importacao'], unique=False)
    op.create_index(op.f('ix_wh_operacao_remessa_fundo_doc'), 'wh_operacao_remessa', ['fundo_doc'], unique=False)
    op.create_index('ix_wh_operacao_remessa_id_operacao', 'wh_operacao_remessa', ['id_operacao_recebivel'], unique=False)
    op.create_index(op.f('ix_wh_operacao_remessa_source_id'), 'wh_operacao_remessa', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_remessa_source_type'), 'wh_operacao_remessa', ['source_type'], unique=False)
    op.create_index('ix_wh_operacao_remessa_tenant_fundo_cedente', 'wh_operacao_remessa', ['tenant_id', 'fundo_doc', 'cedente_doc', 'data_importacao'], unique=False)
    op.create_index('ix_wh_operacao_remessa_tenant_fundo_data', 'wh_operacao_remessa', ['tenant_id', 'fundo_doc', 'data_importacao'], unique=False)
    op.create_index(op.f('ix_wh_operacao_remessa_tenant_id'), 'wh_operacao_remessa', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_operacao_remessa_tenant_id'), table_name='wh_operacao_remessa')
    op.drop_index('ix_wh_operacao_remessa_tenant_fundo_data', table_name='wh_operacao_remessa')
    op.drop_index('ix_wh_operacao_remessa_tenant_fundo_cedente', table_name='wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_operacao_remessa_source_type'), table_name='wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_operacao_remessa_source_id'), table_name='wh_operacao_remessa')
    op.drop_index('ix_wh_operacao_remessa_id_operacao', table_name='wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_operacao_remessa_fundo_doc'), table_name='wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_operacao_remessa_data_importacao'), table_name='wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_operacao_remessa_cedente_doc'), table_name='wh_operacao_remessa')
    op.drop_table('wh_operacao_remessa')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_tipo_recebivel'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_tenant_id'), table_name='wh_liquidacao_recebivel')
    op.drop_index('ix_wh_liquidacao_recebivel_tenant_fundo_sacado', table_name='wh_liquidacao_recebivel')
    op.drop_index('ix_wh_liquidacao_recebivel_tenant_fundo_data', table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_st_recebivel'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_source_type'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_source_id'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_sacado_doc'), table_name='wh_liquidacao_recebivel')
    op.drop_index('ix_wh_liquidacao_recebivel_id_recebivel', table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_fundo_doc'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_data_posicao'), table_name='wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_liquidacao_recebivel_cedente_doc'), table_name='wh_liquidacao_recebivel')
    op.drop_table('wh_liquidacao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_tipo_recebivel'), table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_tenant_id'), table_name='wh_aquisicao_recebivel')
    op.drop_index('ix_wh_aquisicao_recebivel_tenant_fundo_sacado', table_name='wh_aquisicao_recebivel')
    op.drop_index('ix_wh_aquisicao_recebivel_tenant_fundo_data', table_name='wh_aquisicao_recebivel')
    op.drop_index('ix_wh_aquisicao_recebivel_tenant_fundo_cedente', table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_source_type'), table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_source_id'), table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_sacado_doc'), table_name='wh_aquisicao_recebivel')
    op.drop_index('ix_wh_aquisicao_recebivel_id_recebivel', table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_fundo_doc'), table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_data_aquisicao'), table_name='wh_aquisicao_recebivel')
    op.drop_index(op.f('ix_wh_aquisicao_recebivel_cedente_doc'), table_name='wh_aquisicao_recebivel')
    op.drop_table('wh_aquisicao_recebivel')
    # ### end Alembic commands ###
