"""warehouse: add uq (tenant_id, source_id) for dims and dre

Revision ID: 11f533fcddd2
Revises: 25a3ad5c782c
Create Date: 2026-04-20 17:20:10.130550

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11f533fcddd2'
down_revision: str | None = '25a3ad5c782c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wh_dim_dre_classificacao_source', 'wh_dim_dre_classificacao', ['tenant_id', 'source_id'])
    op.create_unique_constraint('uq_wh_dim_mes_source', 'wh_dim_mes', ['tenant_id', 'source_id'])
    op.create_unique_constraint('uq_wh_dre_mensal_source', 'wh_dre_mensal', ['tenant_id', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wh_dre_mensal_source', 'wh_dre_mensal', type_='unique')
    op.drop_constraint('uq_wh_dim_mes_source', 'wh_dim_mes', type_='unique')
    op.drop_constraint('uq_wh_dim_dre_classificacao_source', 'wh_dim_dre_classificacao', type_='unique')
    # ### end Alembic commands ###
