"""warehouse: wh_qitech_raw_relatorio

Revision ID: 1368b623728e
Revises: fc553fadc058
Create Date: 2026-04-25 11:27:31.494607

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1368b623728e'
down_revision: str | None = 'fc553fadc058'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_qitech_raw_relatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo_de_mercado', sa.String(length=50), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_by_version', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tipo_de_mercado', 'data_posicao', name='uq_wh_qitech_raw_relatorio')
    )
    op.create_index(op.f('ix_wh_qitech_raw_relatorio_data_posicao'), 'wh_qitech_raw_relatorio', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_qitech_raw_relatorio_payload_sha256'), 'wh_qitech_raw_relatorio', ['payload_sha256'], unique=False)
    op.create_index(op.f('ix_wh_qitech_raw_relatorio_tenant_id'), 'wh_qitech_raw_relatorio', ['tenant_id'], unique=False)
    op.create_index('ix_wh_qitech_raw_relatorio_tenant_tipo_data', 'wh_qitech_raw_relatorio', ['tenant_id', 'tipo_de_mercado', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_qitech_raw_relatorio_tipo_de_mercado'), 'wh_qitech_raw_relatorio', ['tipo_de_mercado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_qitech_raw_relatorio_tipo_de_mercado'), table_name='wh_qitech_raw_relatorio')
    op.drop_index('ix_wh_qitech_raw_relatorio_tenant_tipo_data', table_name='wh_qitech_raw_relatorio')
    op.drop_index(op.f('ix_wh_qitech_raw_relatorio_tenant_id'), table_name='wh_qitech_raw_relatorio')
    op.drop_index(op.f('ix_wh_qitech_raw_relatorio_payload_sha256'), table_name='wh_qitech_raw_relatorio')
    op.drop_index(op.f('ix_wh_qitech_raw_relatorio_data_posicao'), table_name='wh_qitech_raw_relatorio')
    op.drop_table('wh_qitech_raw_relatorio')
    # ### end Alembic commands ###
