"""warehouse: titulo_snapshot operacao titulo dre dims

Revision ID: 25a3ad5c782c
Revises: 64feb2501ac9
Create Date: 2026-04-20 16:41:51.745676

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '25a3ad5c782c'
down_revision: str | None = '64feb2501ac9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_dim_dre_classificacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('classificacao_id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=False),
    sa.Column('grupo_dre', sa.String(length=50), nullable=False),
    sa.Column('subgrupo', sa.String(length=100), nullable=False),
    sa.Column('ordem_grupo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'classificacao_id', name='uq_wh_dim_dre_classificacao')
    )
    op.create_index(op.f('ix_wh_dim_dre_classificacao_grupo_dre'), 'wh_dim_dre_classificacao', ['grupo_dre'], unique=False)
    op.create_index(op.f('ix_wh_dim_dre_classificacao_source_id'), 'wh_dim_dre_classificacao', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_dre_classificacao_source_type'), 'wh_dim_dre_classificacao', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_dim_dre_classificacao_tenant_id'), 'wh_dim_dre_classificacao', ['tenant_id'], unique=False)
    op.create_table('wh_dim_mes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mes_ano', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('ano_mes_texto', sa.String(length=7), nullable=False),
    sa.Column('mes_nome', sa.String(length=9), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'mes_ano', name='uq_wh_dim_mes')
    )
    op.create_index(op.f('ix_wh_dim_mes_mes_ano'), 'wh_dim_mes', ['mes_ano'], unique=False)
    op.create_index(op.f('ix_wh_dim_mes_source_id'), 'wh_dim_mes', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_mes_source_type'), 'wh_dim_mes', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_dim_mes_tenant_id'), 'wh_dim_mes', ['tenant_id'], unique=False)
    op.create_table('wh_dre_mensal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('ordem_grupo', sa.Integer(), nullable=False),
    sa.Column('grupo_dre', sa.String(length=50), nullable=False),
    sa.Column('subgrupo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('fornecedor_documento', sa.String(length=20), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('unidade_administrativa_id', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('receita', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('custo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('resultado', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'competencia', 'grupo_dre', 'subgrupo', 'descricao', 'entidade_id', 'produto_id', 'fonte', name='uq_wh_dre_mensal')
    )
    op.create_index(op.f('ix_wh_dre_mensal_ano'), 'wh_dre_mensal', ['ano'], unique=False)
    op.create_index(op.f('ix_wh_dre_mensal_competencia'), 'wh_dre_mensal', ['competencia'], unique=False)
    op.create_index(op.f('ix_wh_dre_mensal_grupo_dre'), 'wh_dre_mensal', ['grupo_dre'], unique=False)
    op.create_index(op.f('ix_wh_dre_mensal_source_id'), 'wh_dre_mensal', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_dre_mensal_source_type'), 'wh_dre_mensal', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_dre_mensal_tenant_id'), 'wh_dre_mensal', ['tenant_id'], unique=False)
    op.create_table('wh_operacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('data_de_cadastro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_de_efetivacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('efetivada', sa.Boolean(), nullable=False),
    sa.Column('quantidade_de_titulos', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=10), nullable=False),
    sa.Column('coobrigacao', sa.Boolean(), nullable=False),
    sa.Column('codigo_de_registro', sa.String(length=200), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('conta_operacional_id', sa.Integer(), nullable=False),
    sa.Column('unidade_administrativa_id', sa.Integer(), nullable=False),
    sa.Column('prazo_medio_real', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('prazo_medio_cobrado', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_liquido', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_de_juros', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_de_ad_valorem', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_de_iof', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_de_imposto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_de_rebate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_medio_dos_titulos', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_medio_por_sacado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantidade_de_sacados', sa.Integer(), nullable=False),
    sa.Column('taxa_de_juros', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('taxa_de_ad_valorem', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('taxa_de_iof', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('taxa_de_imposto', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('taxa_de_rebate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('spread', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('fator_de_desconto_cobrado', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fator_de_desconto_real', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('floating_para_prazo', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_das_consultas_financeiras', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_dos_registros_bancarios', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_das_consultas_fiscais', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_dos_comunicados_de_cessao', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_dos_documentos_digitais', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_dos_descontos_ou_abatimentos', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_do_ultimo_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_operacao')
    )
    op.create_index(op.f('ix_wh_operacao_data_de_efetivacao'), 'wh_operacao', ['data_de_efetivacao'], unique=False)
    op.create_index(op.f('ix_wh_operacao_efetivada'), 'wh_operacao', ['efetivada'], unique=False)
    op.create_index(op.f('ix_wh_operacao_modalidade'), 'wh_operacao', ['modalidade'], unique=False)
    op.create_index(op.f('ix_wh_operacao_operacao_id'), 'wh_operacao', ['operacao_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_source_id'), 'wh_operacao', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_source_type'), 'wh_operacao', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_operacao_tenant_id'), 'wh_operacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_unidade_administrativa_id'), 'wh_operacao', ['unidade_administrativa_id'], unique=False)
    op.create_table('wh_operacao_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('item_da_operacao_id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=True),
    sa.Column('titulo_id', sa.Integer(), nullable=True),
    sa.Column('valor_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_presente', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_de_juros', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_do_ad_valorem', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_do_iof', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_do_rebate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('saldo_devedor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('prazo_real', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('prazo_cobrado', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('data_de_vencimento_original', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sugerido_para_exclusao', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_operacao_item')
    )
    op.create_index(op.f('ix_wh_operacao_item_item_da_operacao_id'), 'wh_operacao_item', ['item_da_operacao_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_item_operacao_id'), 'wh_operacao_item', ['operacao_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_item_source_id'), 'wh_operacao_item', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_item_source_type'), 'wh_operacao_item', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_operacao_item_tenant_id'), 'wh_operacao_item', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_operacao_item_titulo_id'), 'wh_operacao_item', ['titulo_id'], unique=False)
    op.create_table('wh_titulo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('titulo_id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=4), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('data_de_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_de_vencimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_de_vencimento_efetiva', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_de_cadastro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_da_situacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_do_status', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_do_pagamento', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('saldo_devedor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('meio', sa.String(length=30), nullable=True),
    sa.Column('sacado_id', sa.Integer(), nullable=False),
    sa.Column('conta_operacional_id', sa.Integer(), nullable=False),
    sa.Column('unidade_administrativa_id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('subscricao_id', sa.Integer(), nullable=True),
    sa.Column('retencao_id', sa.Integer(), nullable=True),
    sa.Column('data_permitida_para_protesto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_da_solicitacao_do_protesto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_do_envio_ao_cartorio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_do_protesto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_da_sustacao_do_protesto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_do_cancelamento_do_protesto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sustado_judicialmente', sa.Boolean(), nullable=False),
    sa.Column('data_permitida_para_negativacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_da_negativacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_do_cancelamento_da_negativacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('codigo_de_registro', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_titulo')
    )
    op.create_index(op.f('ix_wh_titulo_data_de_vencimento_efetiva'), 'wh_titulo', ['data_de_vencimento_efetiva'], unique=False)
    op.create_index(op.f('ix_wh_titulo_operacao_id'), 'wh_titulo', ['operacao_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_sacado_id'), 'wh_titulo', ['sacado_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_saldo_devedor'), 'wh_titulo', ['saldo_devedor'], unique=False)
    op.create_index(op.f('ix_wh_titulo_situacao'), 'wh_titulo', ['situacao'], unique=False)
    op.create_index(op.f('ix_wh_titulo_source_id'), 'wh_titulo', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_source_type'), 'wh_titulo', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_titulo_status'), 'wh_titulo', ['status'], unique=False)
    op.create_index(op.f('ix_wh_titulo_tenant_id'), 'wh_titulo', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_titulo_id'), 'wh_titulo', ['titulo_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_unidade_administrativa_id'), 'wh_titulo', ['unidade_administrativa_id'], unique=False)
    op.create_table('wh_titulo_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('unidade_administrativa_id', sa.Integer(), nullable=True),
    sa.Column('sacado_id', sa.Integer(), nullable=True),
    sa.Column('coobrigacao', sa.Boolean(), nullable=True),
    sa.Column('produto_sigla', sa.String(length=20), nullable=True),
    sa.Column('produto_descricao', sa.String(length=200), nullable=True),
    sa.Column('recebivel_sigla', sa.String(length=20), nullable=True),
    sa.Column('recebivel_descricao', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.Integer(), nullable=True),
    sa.Column('situacao_descricao', sa.String(length=100), nullable=True),
    sa.Column('cedente_cliente_id', sa.Integer(), nullable=True),
    sa.Column('cedente_entidade_id', sa.Integer(), nullable=True),
    sa.Column('cedente_nome', sa.String(length=300), nullable=True),
    sa.Column('cedente_documento', sa.String(length=50), nullable=True),
    sa.Column('grupo_economico_id_cedente', sa.Integer(), nullable=True),
    sa.Column('grupo_economico_nome_cedente', sa.String(length=300), nullable=True),
    sa.Column('cedente_em_rj', sa.Boolean(), nullable=True),
    sa.Column('cedente_chave_cnae', sa.String(length=20), nullable=True),
    sa.Column('cnae_secao', sa.String(length=20), nullable=True),
    sa.Column('cnae_divisao', sa.String(length=20), nullable=True),
    sa.Column('cnae_grupo', sa.String(length=20), nullable=True),
    sa.Column('cnae_classe', sa.String(length=20), nullable=True),
    sa.Column('cnae_subclasse', sa.String(length=20), nullable=True),
    sa.Column('cnae_denominacao', sa.String(length=300), nullable=True),
    sa.Column('sacado_entidade_id', sa.Integer(), nullable=True),
    sa.Column('sacado_nome', sa.String(length=300), nullable=True),
    sa.Column('sacado_documento', sa.String(length=50), nullable=True),
    sa.Column('grupo_economico_id_sacado', sa.Integer(), nullable=True),
    sa.Column('grupo_economico_nome_sacado', sa.String(length=300), nullable=True),
    sa.Column('sacado_em_rj', sa.Boolean(), nullable=True),
    sa.Column('gerente_nome', sa.String(length=300), nullable=True),
    sa.Column('gerente_documento', sa.String(length=50), nullable=True),
    sa.Column('cedente_grp_key', sa.String(length=50), nullable=True),
    sa.Column('cedente_grp_nome', sa.String(length=300), nullable=True),
    sa.Column('cedente_grp_tipo', sa.String(length=20), nullable=True),
    sa.Column('sacado_grp_key', sa.String(length=50), nullable=True),
    sa.Column('sacado_grp_nome', sa.String(length=300), nullable=True),
    sa.Column('sacado_grp_tipo', sa.String(length=20), nullable=True),
    sa.Column('saldo_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_mais_5_dias', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_d0_a_d5', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_ate_d30', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_ate_d60', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_60_ate_120', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vencido_maior_d120', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('qtd_titulos', sa.Integer(), nullable=True),
    sa.Column('qtd_operacoes', sa.Integer(), nullable=True),
    sa.Column('qtd_cedentes', sa.Integer(), nullable=True),
    sa.Column('qtd_sacados', sa.Integer(), nullable=True),
    sa.Column('ticket_medio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('atraso_max', sa.Integer(), nullable=True),
    sa.Column('atraso_medio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'data_ref', 'source_id', name='uq_wh_titulo_snapshot')
    )
    op.create_index(op.f('ix_wh_titulo_snapshot_cedente_documento'), 'wh_titulo_snapshot', ['cedente_documento'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_cedente_entidade_id'), 'wh_titulo_snapshot', ['cedente_entidade_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_data_ref'), 'wh_titulo_snapshot', ['data_ref'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_produto_sigla'), 'wh_titulo_snapshot', ['produto_sigla'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_sacado_documento'), 'wh_titulo_snapshot', ['sacado_documento'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_sacado_entidade_id'), 'wh_titulo_snapshot', ['sacado_entidade_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_snapshot_id'), 'wh_titulo_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_source_id'), 'wh_titulo_snapshot', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_source_type'), 'wh_titulo_snapshot', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_titulo_snapshot_tenant_id'), 'wh_titulo_snapshot', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_titulo_snapshot_tenant_id'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_source_type'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_source_id'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_snapshot_id'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_sacado_entidade_id'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_sacado_documento'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_produto_sigla'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_data_ref'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_cedente_entidade_id'), table_name='wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_snapshot_cedente_documento'), table_name='wh_titulo_snapshot')
    op.drop_table('wh_titulo_snapshot')
    op.drop_index(op.f('ix_wh_titulo_unidade_administrativa_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_titulo_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_tenant_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_status'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_source_type'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_source_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_situacao'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_saldo_devedor'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_sacado_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_operacao_id'), table_name='wh_titulo')
    op.drop_index(op.f('ix_wh_titulo_data_de_vencimento_efetiva'), table_name='wh_titulo')
    op.drop_table('wh_titulo')
    op.drop_index(op.f('ix_wh_operacao_item_titulo_id'), table_name='wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_item_tenant_id'), table_name='wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_item_source_type'), table_name='wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_item_source_id'), table_name='wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_item_operacao_id'), table_name='wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_item_item_da_operacao_id'), table_name='wh_operacao_item')
    op.drop_table('wh_operacao_item')
    op.drop_index(op.f('ix_wh_operacao_unidade_administrativa_id'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_tenant_id'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_source_type'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_source_id'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_operacao_id'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_modalidade'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_efetivada'), table_name='wh_operacao')
    op.drop_index(op.f('ix_wh_operacao_data_de_efetivacao'), table_name='wh_operacao')
    op.drop_table('wh_operacao')
    op.drop_index(op.f('ix_wh_dre_mensal_tenant_id'), table_name='wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dre_mensal_source_type'), table_name='wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dre_mensal_source_id'), table_name='wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dre_mensal_grupo_dre'), table_name='wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dre_mensal_competencia'), table_name='wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dre_mensal_ano'), table_name='wh_dre_mensal')
    op.drop_table('wh_dre_mensal')
    op.drop_index(op.f('ix_wh_dim_mes_tenant_id'), table_name='wh_dim_mes')
    op.drop_index(op.f('ix_wh_dim_mes_source_type'), table_name='wh_dim_mes')
    op.drop_index(op.f('ix_wh_dim_mes_source_id'), table_name='wh_dim_mes')
    op.drop_index(op.f('ix_wh_dim_mes_mes_ano'), table_name='wh_dim_mes')
    op.drop_table('wh_dim_mes')
    op.drop_index(op.f('ix_wh_dim_dre_classificacao_tenant_id'), table_name='wh_dim_dre_classificacao')
    op.drop_index(op.f('ix_wh_dim_dre_classificacao_source_type'), table_name='wh_dim_dre_classificacao')
    op.drop_index(op.f('ix_wh_dim_dre_classificacao_source_id'), table_name='wh_dim_dre_classificacao')
    op.drop_index(op.f('ix_wh_dim_dre_classificacao_grupo_dre'), table_name='wh_dim_dre_classificacao')
    op.drop_table('wh_dim_dre_classificacao')
    # ### end Alembic commands ###
