"""qitech: report jobs + estoque + payload_text raw

Revision ID: 32a2d607d5c4
Revises: 993215c046ad
Create Date: 2026-04-25 15:50:49.090760

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32a2d607d5c4'
down_revision: str | None = '993215c046ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_estoque_recebivel',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('fundo_doc', sa.String(length=14), nullable=False),
    sa.Column('fundo_nome', sa.String(length=200), nullable=False),
    sa.Column('data_fundo', sa.Date(), nullable=True),
    sa.Column('gestor_doc', sa.String(length=14), nullable=False),
    sa.Column('gestor_nome', sa.String(length=200), nullable=False),
    sa.Column('originador_doc', sa.String(length=14), nullable=False),
    sa.Column('originador_nome', sa.String(length=200), nullable=False),
    sa.Column('cedente_doc', sa.String(length=14), nullable=False),
    sa.Column('cedente_nome', sa.String(length=200), nullable=False),
    sa.Column('sacado_doc', sa.String(length=14), nullable=False),
    sa.Column('sacado_nome', sa.String(length=200), nullable=False),
    sa.Column('seu_numero', sa.String(length=50), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=False),
    sa.Column('tipo_recebivel', sa.String(length=50), nullable=False),
    sa.Column('valor_nominal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_presente', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_aquisicao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_pdd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('faixa_pdd', sa.String(length=5), nullable=False),
    sa.Column('data_vencimento_original', sa.Date(), nullable=True),
    sa.Column('data_vencimento_ajustada', sa.Date(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=False),
    sa.Column('prazo_anual', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('situacao_recebivel', sa.String(length=30), nullable=False),
    sa.Column('taxa_cessao', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('taxa_recebivel', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('coobrigacao', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_estoque_recebivel')
    )
    op.create_index(op.f('ix_wh_estoque_recebivel_cedente_doc'), 'wh_estoque_recebivel', ['cedente_doc'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_data_referencia'), 'wh_estoque_recebivel', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_faixa_pdd'), 'wh_estoque_recebivel', ['faixa_pdd'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_fundo_doc'), 'wh_estoque_recebivel', ['fundo_doc'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_sacado_doc'), 'wh_estoque_recebivel', ['sacado_doc'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_seu_numero'), 'wh_estoque_recebivel', ['seu_numero'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_situacao_recebivel'), 'wh_estoque_recebivel', ['situacao_recebivel'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_source_id'), 'wh_estoque_recebivel', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_source_type'), 'wh_estoque_recebivel', ['source_type'], unique=False)
    op.create_index('ix_wh_estoque_recebivel_tenant_fundo_cedente', 'wh_estoque_recebivel', ['tenant_id', 'fundo_doc', 'cedente_doc', 'data_referencia'], unique=False)
    op.create_index('ix_wh_estoque_recebivel_tenant_fundo_data', 'wh_estoque_recebivel', ['tenant_id', 'fundo_doc', 'data_referencia'], unique=False)
    op.create_index('ix_wh_estoque_recebivel_tenant_fundo_pdd', 'wh_estoque_recebivel', ['tenant_id', 'fundo_doc', 'faixa_pdd', 'data_referencia'], unique=False)
    op.create_index('ix_wh_estoque_recebivel_tenant_fundo_sacado_data', 'wh_estoque_recebivel', ['tenant_id', 'fundo_doc', 'sacado_doc', 'data_referencia'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_tenant_id'), 'wh_estoque_recebivel', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_estoque_recebivel_tipo_recebivel'), 'wh_estoque_recebivel', ['tipo_recebivel'], unique=False)
    op.create_table('qitech_report_job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('SANDBOX', 'PRODUCTION', name='environment', native_enum=False, length=16), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('cnpj_fundo', sa.String(length=14), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qitech_job_id', sa.String(length=80), nullable=False),
    sa.Column('qitech_webhook_id', sa.Integer(), nullable=True),
    sa.Column('callback_url_used', sa.Text(), nullable=False),
    sa.Column('callback_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROCESSING', 'SUCCESS', 'CANCELED', 'ERROR', 'TIMEOUT', name='qitech_job_status', native_enum=False, length=16), nullable=False),
    sa.Column('result_file_link', sa.Text(), nullable=True),
    sa.Column('result_file_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_relatorio_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_relatorio_id'], ['wh_qitech_raw_relatorio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qitech_job_id', name='uq_qitech_report_job_qitech_job_id')
    )
    op.create_index(op.f('ix_qitech_report_job_cnpj_fundo'), 'qitech_report_job', ['cnpj_fundo'], unique=False)
    op.create_index('ix_qitech_report_job_lookup', 'qitech_report_job', ['tenant_id', 'report_type', 'cnpj_fundo', 'reference_date', 'status'], unique=False)
    op.create_index(op.f('ix_qitech_report_job_qitech_job_id'), 'qitech_report_job', ['qitech_job_id'], unique=False)
    op.create_index(op.f('ix_qitech_report_job_reference_date'), 'qitech_report_job', ['reference_date'], unique=False)
    op.create_index(op.f('ix_qitech_report_job_report_type'), 'qitech_report_job', ['report_type'], unique=False)
    op.create_index(op.f('ix_qitech_report_job_status'), 'qitech_report_job', ['status'], unique=False)
    op.create_index('ix_qitech_report_job_status_created', 'qitech_report_job', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_qitech_report_job_tenant_id'), 'qitech_report_job', ['tenant_id'], unique=False)
    op.add_column('wh_qitech_raw_relatorio', sa.Column('payload_text', sa.Text(), nullable=True))
    op.alter_column('wh_qitech_raw_relatorio', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wh_qitech_raw_relatorio', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('wh_qitech_raw_relatorio', 'payload_text')
    op.drop_index(op.f('ix_qitech_report_job_tenant_id'), table_name='qitech_report_job')
    op.drop_index('ix_qitech_report_job_status_created', table_name='qitech_report_job')
    op.drop_index(op.f('ix_qitech_report_job_status'), table_name='qitech_report_job')
    op.drop_index(op.f('ix_qitech_report_job_report_type'), table_name='qitech_report_job')
    op.drop_index(op.f('ix_qitech_report_job_reference_date'), table_name='qitech_report_job')
    op.drop_index(op.f('ix_qitech_report_job_qitech_job_id'), table_name='qitech_report_job')
    op.drop_index('ix_qitech_report_job_lookup', table_name='qitech_report_job')
    op.drop_index(op.f('ix_qitech_report_job_cnpj_fundo'), table_name='qitech_report_job')
    op.drop_table('qitech_report_job')
    op.drop_index(op.f('ix_wh_estoque_recebivel_tipo_recebivel'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_tenant_id'), table_name='wh_estoque_recebivel')
    op.drop_index('ix_wh_estoque_recebivel_tenant_fundo_sacado_data', table_name='wh_estoque_recebivel')
    op.drop_index('ix_wh_estoque_recebivel_tenant_fundo_pdd', table_name='wh_estoque_recebivel')
    op.drop_index('ix_wh_estoque_recebivel_tenant_fundo_data', table_name='wh_estoque_recebivel')
    op.drop_index('ix_wh_estoque_recebivel_tenant_fundo_cedente', table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_source_type'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_source_id'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_situacao_recebivel'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_seu_numero'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_sacado_doc'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_fundo_doc'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_faixa_pdd'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_data_referencia'), table_name='wh_estoque_recebivel')
    op.drop_index(op.f('ix_wh_estoque_recebivel_cedente_doc'), table_name='wh_estoque_recebivel')
    op.drop_table('wh_estoque_recebivel')
    # ### end Alembic commands ###
