"""cadastros: unidade administrativa

Revision ID: 40c76a6cec65
Revises: 1368b623728e
Create Date: 2026-04-25 12:08:22.635397

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40c76a6cec65'
down_revision: str | None = '1368b623728e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_unidade_administrativa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('tipo', sa.Enum('FIDC', 'CONSULTORIA', 'SECURITIZADORA', 'FACTORING', 'GESTORA', name='tipo_unidade_administrativa', native_enum=False, length=32), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bitfin_ua_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_cadastros_ua_tenant_nome')
    )
    op.create_index('ix_cadastros_ua_tenant_ativa', 'cadastros_unidade_administrativa', ['tenant_id', 'ativa'], unique=False)
    op.create_index(op.f('ix_cadastros_unidade_administrativa_tenant_id'), 'cadastros_unidade_administrativa', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cadastros_unidade_administrativa_tipo'), 'cadastros_unidade_administrativa', ['tipo'], unique=False)
    op.create_index('uq_cadastros_ua_tenant_cnpj', 'cadastros_unidade_administrativa', ['tenant_id', 'cnpj'], unique=True, postgresql_where=sa.text('cnpj IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cadastros_ua_tenant_cnpj', table_name='cadastros_unidade_administrativa', postgresql_where=sa.text('cnpj IS NOT NULL'))
    op.drop_index(op.f('ix_cadastros_unidade_administrativa_tipo'), table_name='cadastros_unidade_administrativa')
    op.drop_index(op.f('ix_cadastros_unidade_administrativa_tenant_id'), table_name='cadastros_unidade_administrativa')
    op.drop_index('ix_cadastros_ua_tenant_ativa', table_name='cadastros_unidade_administrativa')
    op.drop_table('cadastros_unidade_administrativa')
    # ### end Alembic commands ###
