"""initial schema: identity + audit_log + catalog

Revision ID: 64feb2501ac9
Revises:
Create Date: 2026-04-20 13:36:34.450770

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64feb2501ac9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_catalog",
        sa.Column(
            "source_type",
            sa.Enum(
                "ERP_BITFIN",
                "ADMIN_QITECH",
                "BUREAU_SERASA_REFINHO",
                "BUREAU_SERASA_PFIN",
                "BUREAU_SCR_BACEN",
                "DOCUMENT_NFE",
                "SELF_DECLARED",
                "PEER_DECLARED",
                "INTERNAL_NOTE",
                "DERIVED",
                name="source_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("owner_org", sa.String(length=128), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("unit_cost_brl", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_type"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subdomain", sa.String(length=100), nullable=True),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subdomain"),
    )
    op.create_index(op.f("ix_tenants_ativo"), "tenants", ["ativo"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "tenant_module_subscription",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "module",
            sa.Enum(
                "BI",
                "CADASTROS",
                "OPERACOES",
                "CONTROLADORIA",
                "RISCO",
                "INTEGRACOES",
                "LABORATORIO",
                "ADMIN",
                name="module",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enabled_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plan_ref", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "module"),
    )
    op.create_index(
        op.f("ix_tenant_module_subscription_enabled"),
        "tenant_module_subscription",
        ["enabled"],
        unique=False,
    )
    op.create_table(
        "tenant_source_config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "ERP_BITFIN",
                "ADMIN_QITECH",
                "BUREAU_SERASA_REFINHO",
                "BUREAU_SERASA_PFIN",
                "BUREAU_SCR_BACEN",
                "DOCUMENT_NFE",
                "SELF_DECLARED",
                "PEER_DECLARED",
                "INTERNAL_NOTE",
                "DERIVED",
                name="source_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sync_frequency_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_type"],
            ["source_catalog.source_type"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_type", name="uq_tenant_source"),
    )
    op.create_index(
        op.f("ix_tenant_source_config_enabled"), "tenant_source_config", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_source_config_tenant_id"),
        "tenant_source_config",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_tenant_email"),
    )
    op.create_index(op.f("ix_users_ativo"), "users", ["ativo"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "premise_set",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("premises", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", "version", name="uq_premise_set_key_version"),
    )
    op.create_index(op.f("ix_premise_set_key"), "premise_set", ["key"], unique=False)
    op.create_index(op.f("ix_premise_set_tenant_id"), "premise_set", ["tenant_id"], unique=False)
    op.create_table(
        "user_module_permission",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "module",
            sa.Enum(
                "BI",
                "CADASTROS",
                "OPERACOES",
                "CONTROLADORIA",
                "RISCO",
                "INTEGRACOES",
                "LABORATORIO",
                "ADMIN",
                name="module",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "permission",
            sa.Enum(
                "NONE", "READ", "WRITE", "ADMIN", name="permission", native_enum=False, length=16
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "module"),
    )
    op.create_table(
        "decision_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "decision_type",
            sa.Enum(
                "SYNC",
                "CALCULATION",
                "ALERT",
                "RECOMMENDATION",
                "SCORE",
                "RECONCILIATION_CHECK",
                "RULE_EVALUATION",
                name="decision_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("inputs_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_or_model", sa.String(length=128), nullable=True),
        sa.Column("rule_or_model_version", sa.String(length=64), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.String(length=128), nullable=False),
        sa.Column("supersedes", sa.UUID(), nullable=True),
        sa.Column("premise_set_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["premise_set_id"],
            ["premise_set.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes"],
            ["decision_log.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_log_decision_type"), "decision_log", ["decision_type"], unique=False
    )
    op.create_index(
        op.f("ix_decision_log_occurred_at"), "decision_log", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_decision_log_tenant_id"), "decision_log", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decision_log_tenant_id"), table_name="decision_log")
    op.drop_index(op.f("ix_decision_log_occurred_at"), table_name="decision_log")
    op.drop_index(op.f("ix_decision_log_decision_type"), table_name="decision_log")
    op.drop_table("decision_log")
    op.drop_table("user_module_permission")
    op.drop_index(op.f("ix_premise_set_tenant_id"), table_name="premise_set")
    op.drop_index(op.f("ix_premise_set_key"), table_name="premise_set")
    op.drop_table("premise_set")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_ativo"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenant_source_config_tenant_id"), table_name="tenant_source_config")
    op.drop_index(op.f("ix_tenant_source_config_enabled"), table_name="tenant_source_config")
    op.drop_table("tenant_source_config")
    op.drop_index(
        op.f("ix_tenant_module_subscription_enabled"), table_name="tenant_module_subscription"
    )
    op.drop_table("tenant_module_subscription")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_ativo"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_table("source_catalog")
    # ### end Alembic commands ###
