"""warehouse: wh_rentabilidade_fundo

Revision ID: 65ff6d536bf2
Revises: 684f1f0389e0
Create Date: 2026-04-25 13:07:34.521427

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65ff6d536bf2'
down_revision: str | None = '684f1f0389e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_rentabilidade_fundo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('carteira_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('carteira_cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('carteira_cliente_doc', sa.String(length=14), nullable=False),
    sa.Column('indexador', sa.String(length=20), nullable=False),
    sa.Column('percentual_bench_mark', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_real', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_diaria', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_mensal', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_anual', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_6_meses', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rentabilidade_12_meses', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('valor_patrimonio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('codigo_isin', sa.String(length=20), nullable=True),
    sa.Column('percentual_6_meses', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('percentual_12_meses', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_rentabilidade_fundo')
    )
    op.create_index(op.f('ix_wh_rentabilidade_fundo_carteira_cliente_doc'), 'wh_rentabilidade_fundo', ['carteira_cliente_doc'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_carteira_cliente_id'), 'wh_rentabilidade_fundo', ['carteira_cliente_id'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_data_posicao'), 'wh_rentabilidade_fundo', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_indexador'), 'wh_rentabilidade_fundo', ['indexador'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_source_id'), 'wh_rentabilidade_fundo', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_source_type'), 'wh_rentabilidade_fundo', ['source_type'], unique=False)
    op.create_index('ix_wh_rentabilidade_fundo_tenant_carteira', 'wh_rentabilidade_fundo', ['tenant_id', 'carteira_cliente_doc', 'data_posicao'], unique=False)
    op.create_index('ix_wh_rentabilidade_fundo_tenant_data', 'wh_rentabilidade_fundo', ['tenant_id', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_rentabilidade_fundo_tenant_id'), 'wh_rentabilidade_fundo', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_tenant_id'), table_name='wh_rentabilidade_fundo')
    op.drop_index('ix_wh_rentabilidade_fundo_tenant_data', table_name='wh_rentabilidade_fundo')
    op.drop_index('ix_wh_rentabilidade_fundo_tenant_carteira', table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_source_type'), table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_source_id'), table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_indexador'), table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_data_posicao'), table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_carteira_cliente_id'), table_name='wh_rentabilidade_fundo')
    op.drop_index(op.f('ix_wh_rentabilidade_fundo_carteira_cliente_doc'), table_name='wh_rentabilidade_fundo')
    op.drop_table('wh_rentabilidade_fundo')
    # ### end Alembic commands ###
