"""warehouse: wh_mec_evolucao_cotas

Revision ID: 684f1f0389e0
Revises: 729e2b20f466
Create Date: 2026-04-25 13:04:34.979527

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '684f1f0389e0'
down_revision: str | None = '729e2b20f466'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_mec_evolucao_cotas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('carteira_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('carteira_cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('carteira_cliente_doc', sa.String(length=14), nullable=False),
    sa.Column('entradas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saidas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('aporte', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retirada', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('patrimonio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('valor_da_cota', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('variacao_diaria', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('variacao_mensal', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('variacao_anual', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('variacao_total', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_mec_evolucao_cotas')
    )
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_carteira_cliente_doc'), 'wh_mec_evolucao_cotas', ['carteira_cliente_doc'], unique=False)
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_carteira_cliente_id'), 'wh_mec_evolucao_cotas', ['carteira_cliente_id'], unique=False)
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_data_posicao'), 'wh_mec_evolucao_cotas', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_source_id'), 'wh_mec_evolucao_cotas', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_source_type'), 'wh_mec_evolucao_cotas', ['source_type'], unique=False)
    op.create_index('ix_wh_mec_evolucao_cotas_tenant_carteira', 'wh_mec_evolucao_cotas', ['tenant_id', 'carteira_cliente_doc', 'data_posicao'], unique=False)
    op.create_index('ix_wh_mec_evolucao_cotas_tenant_data', 'wh_mec_evolucao_cotas', ['tenant_id', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_mec_evolucao_cotas_tenant_id'), 'wh_mec_evolucao_cotas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_tenant_id'), table_name='wh_mec_evolucao_cotas')
    op.drop_index('ix_wh_mec_evolucao_cotas_tenant_data', table_name='wh_mec_evolucao_cotas')
    op.drop_index('ix_wh_mec_evolucao_cotas_tenant_carteira', table_name='wh_mec_evolucao_cotas')
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_source_type'), table_name='wh_mec_evolucao_cotas')
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_source_id'), table_name='wh_mec_evolucao_cotas')
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_data_posicao'), table_name='wh_mec_evolucao_cotas')
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_carteira_cliente_id'), table_name='wh_mec_evolucao_cotas')
    op.drop_index(op.f('ix_wh_mec_evolucao_cotas_carteira_cliente_doc'), table_name='wh_mec_evolucao_cotas')
    op.drop_table('wh_mec_evolucao_cotas')
    # ### end Alembic commands ###
