"""warehouse: wh_cpr_movimento

Revision ID: 729e2b20f466
Revises: 03a6eff064c0
Create Date: 2026-04-25 13:01:28.451671

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '729e2b20f466'
down_revision: str | None = '03a6eff064c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_cpr_movimento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('carteira_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('carteira_cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('carteira_cliente_doc', sa.String(length=14), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('historico_traduzido', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percentual_sobre_cpr', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('percentual_sobre_total', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_cpr_movimento')
    )
    op.create_index(op.f('ix_wh_cpr_movimento_carteira_cliente_doc'), 'wh_cpr_movimento', ['carteira_cliente_doc'], unique=False)
    op.create_index(op.f('ix_wh_cpr_movimento_carteira_cliente_id'), 'wh_cpr_movimento', ['carteira_cliente_id'], unique=False)
    op.create_index(op.f('ix_wh_cpr_movimento_data_posicao'), 'wh_cpr_movimento', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_cpr_movimento_source_id'), 'wh_cpr_movimento', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_cpr_movimento_source_type'), 'wh_cpr_movimento', ['source_type'], unique=False)
    op.create_index('ix_wh_cpr_movimento_tenant_carteira', 'wh_cpr_movimento', ['tenant_id', 'carteira_cliente_doc', 'data_posicao'], unique=False)
    op.create_index('ix_wh_cpr_movimento_tenant_data', 'wh_cpr_movimento', ['tenant_id', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_cpr_movimento_tenant_id'), 'wh_cpr_movimento', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_cpr_movimento_tenant_id'), table_name='wh_cpr_movimento')
    op.drop_index('ix_wh_cpr_movimento_tenant_data', table_name='wh_cpr_movimento')
    op.drop_index('ix_wh_cpr_movimento_tenant_carteira', table_name='wh_cpr_movimento')
    op.drop_index(op.f('ix_wh_cpr_movimento_source_type'), table_name='wh_cpr_movimento')
    op.drop_index(op.f('ix_wh_cpr_movimento_source_id'), table_name='wh_cpr_movimento')
    op.drop_index(op.f('ix_wh_cpr_movimento_data_posicao'), table_name='wh_cpr_movimento')
    op.drop_index(op.f('ix_wh_cpr_movimento_carteira_cliente_id'), table_name='wh_cpr_movimento')
    op.drop_index(op.f('ix_wh_cpr_movimento_carteira_cliente_doc'), table_name='wh_cpr_movimento')
    op.drop_table('wh_cpr_movimento')
    # ### end Alembic commands ###
