"""warehouse: wh_movimento_aberto

Revision ID: 733528384336
Revises: 03c0d6a48f32
Create Date: 2026-04-25 17:37:52.793965

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '733528384336'
down_revision: str | None = '03c0d6a48f32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_movimento_aberto',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('fundo_doc', sa.String(length=14), nullable=False),
    sa.Column('fundo_nome', sa.String(length=200), nullable=False),
    sa.Column('seu_numero', sa.String(length=50), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=80), nullable=False),
    sa.Column('valor_aquisicao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_nominal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_movimentacao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_movimento_aberto')
    )
    op.create_index(op.f('ix_wh_movimento_aberto_data_referencia'), 'wh_movimento_aberto', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_wh_movimento_aberto_fundo_doc'), 'wh_movimento_aberto', ['fundo_doc'], unique=False)
    op.create_index(op.f('ix_wh_movimento_aberto_seu_numero'), 'wh_movimento_aberto', ['seu_numero'], unique=False)
    op.create_index(op.f('ix_wh_movimento_aberto_source_id'), 'wh_movimento_aberto', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_movimento_aberto_source_type'), 'wh_movimento_aberto', ['source_type'], unique=False)
    op.create_index('ix_wh_movimento_aberto_tenant_fundo_ref', 'wh_movimento_aberto', ['tenant_id', 'fundo_doc', 'data_referencia'], unique=False)
    op.create_index('ix_wh_movimento_aberto_tenant_fundo_venc', 'wh_movimento_aberto', ['tenant_id', 'fundo_doc', 'data_vencimento'], unique=False)
    op.create_index(op.f('ix_wh_movimento_aberto_tenant_id'), 'wh_movimento_aberto', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_movimento_aberto_tenant_id'), table_name='wh_movimento_aberto')
    op.drop_index('ix_wh_movimento_aberto_tenant_fundo_venc', table_name='wh_movimento_aberto')
    op.drop_index('ix_wh_movimento_aberto_tenant_fundo_ref', table_name='wh_movimento_aberto')
    op.drop_index(op.f('ix_wh_movimento_aberto_source_type'), table_name='wh_movimento_aberto')
    op.drop_index(op.f('ix_wh_movimento_aberto_source_id'), table_name='wh_movimento_aberto')
    op.drop_index(op.f('ix_wh_movimento_aberto_seu_numero'), table_name='wh_movimento_aberto')
    op.drop_index(op.f('ix_wh_movimento_aberto_fundo_doc'), table_name='wh_movimento_aberto')
    op.drop_index(op.f('ix_wh_movimento_aberto_data_referencia'), table_name='wh_movimento_aberto')
    op.drop_table('wh_movimento_aberto')
    # ### end Alembic commands ###
