"""warehouse: wh_posicao_compromissada

Revision ID: 993215c046ad
Revises: 3ba008fdeb37
Create Date: 2026-04-25 13:15:09.472945

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '993215c046ad'
down_revision: str | None = '3ba008fdeb37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_posicao_compromissada',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_posicao', sa.Date(), nullable=False),
    sa.Column('carteira_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('carteira_cliente_nome', sa.String(length=200), nullable=False),
    sa.Column('carteira_cliente_doc', sa.String(length=14), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('papel', sa.String(length=100), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('data_resgate', sa.Date(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('taxa_over', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('taxa_ano', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('pu', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('valor_aplicado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_resgate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percentual_sobre_rf', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('percentual_sobre_total', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('mtm', sa.String(length=50), nullable=True),
    sa.Column('negociacao_vencimento', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_posicao_compromissada')
    )
    op.create_index(op.f('ix_wh_posicao_compromissada_carteira_cliente_doc'), 'wh_posicao_compromissada', ['carteira_cliente_doc'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_carteira_cliente_id'), 'wh_posicao_compromissada', ['carteira_cliente_id'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_codigo'), 'wh_posicao_compromissada', ['codigo'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_data_posicao'), 'wh_posicao_compromissada', ['data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_source_id'), 'wh_posicao_compromissada', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_source_type'), 'wh_posicao_compromissada', ['source_type'], unique=False)
    op.create_index('ix_wh_posicao_compromissada_tenant_carteira', 'wh_posicao_compromissada', ['tenant_id', 'carteira_cliente_doc', 'data_posicao'], unique=False)
    op.create_index('ix_wh_posicao_compromissada_tenant_data', 'wh_posicao_compromissada', ['tenant_id', 'data_posicao'], unique=False)
    op.create_index(op.f('ix_wh_posicao_compromissada_tenant_id'), 'wh_posicao_compromissada', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_posicao_compromissada_tenant_id'), table_name='wh_posicao_compromissada')
    op.drop_index('ix_wh_posicao_compromissada_tenant_data', table_name='wh_posicao_compromissada')
    op.drop_index('ix_wh_posicao_compromissada_tenant_carteira', table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_source_type'), table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_source_id'), table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_data_posicao'), table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_codigo'), table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_carteira_cliente_id'), table_name='wh_posicao_compromissada')
    op.drop_index(op.f('ix_wh_posicao_compromissada_carteira_cliente_doc'), table_name='wh_posicao_compromissada')
    op.drop_table('wh_posicao_compromissada')
    # ### end Alembic commands ###
