"""warehouse: dim produto

Revision ID: e85185ac4d1e
Revises: f552cdabe7f6
Create Date: 2026-04-21 14:19:35.266857

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85185ac4d1e'
down_revision: str | None = 'f552cdabe7f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_dim_produto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_de_contrato', sa.String(length=100), nullable=True),
    sa.Column('produto_de_risco', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'produto_id', name='uq_wh_dim_produto'),
    sa.UniqueConstraint('tenant_id', 'sigla', name='uq_wh_dim_produto_sigla'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_dim_produto_source')
    )
    op.create_index(op.f('ix_wh_dim_produto_produto_id'), 'wh_dim_produto', ['produto_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_produto_sigla'), 'wh_dim_produto', ['sigla'], unique=False)
    op.create_index(op.f('ix_wh_dim_produto_source_id'), 'wh_dim_produto', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_produto_source_type'), 'wh_dim_produto', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_dim_produto_tenant_id'), 'wh_dim_produto', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_dim_produto_tenant_id'), table_name='wh_dim_produto')
    op.drop_index(op.f('ix_wh_dim_produto_source_type'), table_name='wh_dim_produto')
    op.drop_index(op.f('ix_wh_dim_produto_source_id'), table_name='wh_dim_produto')
    op.drop_index(op.f('ix_wh_dim_produto_sigla'), table_name='wh_dim_produto')
    op.drop_index(op.f('ix_wh_dim_produto_produto_id'), table_name='wh_dim_produto')
    op.drop_table('wh_dim_produto')
    # ### end Alembic commands ###
