"""warehouse: dim unidade administrativa

Revision ID: f552cdabe7f6
Revises: 11f533fcddd2
Create Date: 2026-04-21 11:03:03.713474

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f552cdabe7f6'
down_revision: str | None = '11f533fcddd2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh_dim_unidade_administrativa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ua_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.Enum('ERP_BITFIN', 'ADMIN_QITECH', 'BUREAU_SERASA_REFINHO', 'BUREAU_SERASA_PFIN', 'BUREAU_SCR_BACEN', 'DOCUMENT_NFE', 'SELF_DECLARED', 'PEER_DECLARED', 'INTERNAL_NOTE', 'DERIVED', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_origem', sa.String(length=64), nullable=True),
    sa.Column('ingested_by_version', sa.String(length=128), nullable=False),
    sa.Column('trust_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='trust_level', native_enum=False, length=16), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_wh_dim_ua_source'),
    sa.UniqueConstraint('tenant_id', 'ua_id', name='uq_wh_dim_ua')
    )
    op.create_index(op.f('ix_wh_dim_unidade_administrativa_ativa'), 'wh_dim_unidade_administrativa', ['ativa'], unique=False)
    op.create_index(op.f('ix_wh_dim_unidade_administrativa_source_id'), 'wh_dim_unidade_administrativa', ['source_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_unidade_administrativa_source_type'), 'wh_dim_unidade_administrativa', ['source_type'], unique=False)
    op.create_index(op.f('ix_wh_dim_unidade_administrativa_tenant_id'), 'wh_dim_unidade_administrativa', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wh_dim_unidade_administrativa_ua_id'), 'wh_dim_unidade_administrativa', ['ua_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wh_dim_unidade_administrativa_ua_id'), table_name='wh_dim_unidade_administrativa')
    op.drop_index(op.f('ix_wh_dim_unidade_administrativa_tenant_id'), table_name='wh_dim_unidade_administrativa')
    op.drop_index(op.f('ix_wh_dim_unidade_administrativa_source_type'), table_name='wh_dim_unidade_administrativa')
    op.drop_index(op.f('ix_wh_dim_unidade_administrativa_source_id'), table_name='wh_dim_unidade_administrativa')
    op.drop_index(op.f('ix_wh_dim_unidade_administrativa_ativa'), table_name='wh_dim_unidade_administrativa')
    op.drop_table('wh_dim_unidade_administrativa')
    # ### end Alembic commands ###
