"""Pydantic schemas for the AI capability (request/response DTOs)."""

from app.shared.ai.schemas.ai import (
    AgentConfigRead,
    AgentConfigUpdate,
    AgentModelOption,
    AIContext,
    ChatRequest,
    ConversationListItem,
    ConversationMessageRead,
    InsightItem,
    InsightsResponse,
    PromptActivate,
    PromptCreate,
    PromptDetail,
    PromptPreviewRequest,
    PromptPreviewResponse,
    PromptUpdate,
    PromptVersionInfo,
    ProviderCredentialCreate,
    ProviderCredentialRead,
    ProviderCredentialUpdate,
    QuotaResponse,
    TenantAISubscriptionRead,
    TenantAISubscriptionUpdate,
    TopupRequest,
)

__all__ = [
    "AIContext",
    "AgentConfigRead",
    "AgentConfigUpdate",
    "AgentModelOption",
    "ChatRequest",
    "ConversationListItem",
    "ConversationMessageRead",
    "InsightItem",
    "InsightsResponse",
    "PromptActivate",
    "PromptCreate",
    "PromptDetail",
    "PromptPreviewRequest",
    "PromptPreviewResponse",
    "PromptUpdate",
    "PromptVersionInfo",
    "ProviderCredentialCreate",
    "ProviderCredentialRead",
    "ProviderCredentialUpdate",
    "QuotaResponse",
    "TenantAISubscriptionRead",
    "TenantAISubscriptionUpdate",
    "TopupRequest",
]
